name: CI

on:
  push:
    branches: [main, prebuild-electron]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2

      - name: Setup Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.x

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2

      - name: Setup Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.x

      - name: Install
        run: pnpm install

      - name: TypeCheck
        run: pnpm run typecheck

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build:lib

      - name: Unit Test
        run: pnpm run test:run

  prebuild-electron-osx:
    runs-on: ${{ matrix.os }}
    # needs: [lint, typecheck, test]

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.x

      - name: Install
        run: pnpm install

      - name: Configure
        run: pnpm configure

      - name: Prebuild
        run: |
          pnpm config set dist-url "$dist-url"
          pnpm config get dist-url
          pnpm prebuild-electron --upload "$PREBUILD_TOKEN"
        env:
          PREBUILD_TOKEN: ${{ secrets.PREBUILD_TOKEN }}
          dist-url: "https://electronjs.org/headers"

  prebuild-electron-other:
    runs-on: ${{ matrix.os }}
    needs: [lint, typecheck, test]

    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.x

      - name: Install
        run: pnpm install

      - name: Prebuild
        run: |
          pnpm prebuild-electron --upload "$env:PREBUILD_TOKEN"
        env:
          PREBUILD_TOKEN: ${{ secrets.PREBUILD_TOKEN }}
          dist-url: https://electronjs.org/headers

  prebuild:
    runs-on: macos-latest
    needs: [lint, typecheck, test]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2

      - name: Use Node.js 16.14.x
        uses: actions/setup-node@v3.3.0
        with:
          node-version: 16.14.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Prebuild
        run: |
          pnpm upload --upload "$PREBUILD_TOKEN"
        env:
          PREBUILD_TOKEN: ${{ secrets.PREBUILD_TOKEN }}
